instawork/urls.py
from django.contrib import admin
from django.urls import path, include

# hello
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('teammember.urls', namespace='teammember')),
]

teammember/urls.py
from django.urls import path
from . import views

app_name = 'teammember'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('add/', views.AddView.as_view(), name='add'),
    path('posts/', views.PostsView.as_view(), name='posts'),
    path('<slug:slug>/', views.SingleView.as_view(), name='single'),
    path('edit/<int:pk>/', views.EditView.as_view(), name='edit'),
    path('delete/<int:pk>/', views.Delete.as_view(), name='delete'),
]

teammember/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from phone_field import PhoneField

# Create your models here.
class Teammember(models.Model):

    firstName = models.CharField(max_length=200, null=True)
    lastName = models.CharField(max_length=200, null=True)
    email = models.EmailField(max_length=254, null=True)
    phone = PhoneField(blank=True, help_text='Contact phone number')
    is_Regular = models.BooleanField("Regular", default=False)
    is_Admin = models.BooleanField("Admin", default=False)
    updated = models.DateTimeField(auto_now=True)
    published = models.DateTimeField(default=timezone.now)
    
    class Meta:
        ordering = ['-published']

    def __str__(self):
        return self.firstName

teammember/forms.py
from django import forms
from .models import Teammember

NUMS = [
        ('regular','Regular'),
        ('admin', 'Admin'),
        ]

class PostForm(forms.ModelForm):
    class Meta:
        model = Teammember
        fields = "__all__"
        NUMS = forms.ChoiceField(widget=forms.RadioSelect(choices=NUMS))

teammember/views.py
from .models import Teammember
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.urls import reverse_lazy

# Create your views here.
class IndexView(ListView):
    model = Teammember
    template_name = 'teammember/index.html'
    context_object_name = 'index'

class SingleView(DetailView):
    model = Teammember
    template_name = 'teammember/single.html'
    context_object_name = 'post'

class PostsView(ListView):
    model = Teammember
    template_name = 'teammember/posts.html'
    context_object_name = 'teammember_list'

class AddView(CreateView):
    model = Teammember
    template_name = 'teammember/add.html'
    fields = '__all__'
    success_url = '/'

class EditView(UpdateView):
    model = Teammember
    template_name = 'teammember/edit.html'
    fields = '__all__'
    pk_url_kwarg = 'pk'
    success_url = '/'

class Delete(DeleteView):
    model = Teammember
    pk_url_kwarg = 'pk'
    template_name = 'teammember/confirm-delete.html'
    success_url = '/'

teammember/templates/teammember/add.html
{% extends 'teammember/base.html' %}
{% load widget_tweaks %}
{% block content %}

<div class="container pt-5">
    <form method="post" novalidate>
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field|add_class:'form-control' }}
            {% for error in  field.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}
        </div>
        {% endfor %}
        <div class="form-group">
            <button type="submit" class="btn btn-success">
                <span class="glyphicon glyphicon-ok"></span> Edit
            </button>
            <a href="{% url 'teammember:posts' %}" class="btn btn-default">Cancel</a>
        </div>
    </form>
</div>

{% endblock %}

teammember/templates/teammember/base.html
<!doctype html>
<html lang="en">
  <head>
    <title>CRUD app</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    {% include 'teammember/navbar.html' %}
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    {% include 'teammember/footer.html' %}
  </body>
</html> 

teammember/templates/teammember/confirm-delete.html
{% extends 'teammember/base.html' %}
{% block content %}

<div class="container pt-5">
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm">
    </form>
</div>

{% endblock %}

teammember/templates/teammember/edit.html
{% extends 'teammember/base.html' %}
{% load widget_tweaks %}
{% block content %}

<div class="container pt-5">
    <form method="post" novalidate>
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <header>
            <title>Edit team member</title>
        </header>
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field|add_class:'form-control' }}
            {% for error in  field.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}
        </div>
        {% endfor %}
        <div class="form-group">
            <button type="submit" class="btn btn-success">
                <span class="glyphicon glyphicon-ok"></span> Update
            </button>
            <a href="{% url 'teammember:posts' %}" class="btn btn-default">Cancel</a>
        </div>
    </form>
</div>
    </form>
</div>

{% endblock %}

teammember/templates/teammember/footer.html
<div class="container">
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                CMS primer
                <small class="d-block mb-3 text-muted">Another example</small>
            </div>
            <div class="col-12 col-md">
                <h5>About Us</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Home</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

teammember/templates/teammember/index.html
{% extends 'teammember/base.html' %}

{% block content %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'teammember:add' %}"><h2 class="">+</h2></a>
            </li>
        </ul>
    </div>
</nav>

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for member in index %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" src="https://via.placeholder.com/150x100" alt="card-img-top">
                    <div class="card-body">
                        <h4 class=""><a href="{{ member.get_absolute_url }}">{{ member.firstName }}</a></h4>
                        <p class="card-text"></p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{{ member.get_absolute_url }}" class="btn btn-sm btn-outline-primary"
                                    role="button" area-pressed="true">View</a><br>
                                <a href="{% url 'teammember:edit' member.pk %}" class="btn btn-sm btn-outline-secondary"
                                    role="button" area-pressed="true">Edit</a><br>
                                <a href="{% url 'teammember:delete' member.pk %}" class="btn btn-sm btn-outline-secondary" role="button"
                                    area-pressed="true">Delete</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

teammember/templates/teammember/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'teammember:index' %}">Home</a>
          </li>
          <li class="nav-item active">
          </li>
        </ul>
      </div>
    </div>
  </nav>

teammember/templates/teammember/posts.html
{% extends 'teammember/base.html' %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'teammember:add' %}"><h2 class="">+</h2></a>
            </li>
        </ul>
    </div>
</nav>

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for member in teammember_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" src="https://via.placeholder.com/150x100" alt="Card-image-cap">
                    <div class="card-body">
                        <h4 class="lead"><a class="text-dark" href="{% url 'teammember:single' member.pk %}">{{
                                member.firstName }}</a> </h4>
                                <!-- <h4 class=""><a href="{{ member.get_absolute_url }}">{{ member.title }}</a></h4> -->
                        <p class="card-text"></p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{{ member.get_absolute_url }}" class="btn btn-sm btn-outline-primary"
                                    role="button" area-pressed="true">View</a>
                                <a href="{% url 'teammember:edit' member.pk %}" class="btn btn-sm btn-outline-secondary"
                                    role="button" area-pressed="true">Edit</a>
                                <a href="{% url 'teammember:delete' member.pk %}" class="btn btn-sm btn-outline-secondary"
                                    role="button" area-pressed="true">Delete</a>
                            </div>
                            <small class="text-muted">9 mins</small>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

teammember/templates/teammember/single.html
{% extends 'teammember/base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12 pt-5">
            <img class="card-img-top" src="https://via.placeholder.com/300x100" alt="card-img-top">
            <h2 class="pt-5">{{post.firstName}}</h2>
            <p>{{post.firstName}}</p>
        </div>
    </div>
</div>

{% endblock %}